on:
  pull_request:
    branches: ["master"]

name: CI

jobs:

  format:
    runs-on: ubuntu-latest
    if: success() || failure()
    steps:
      - uses: actions/checkout@v3
      - name: Update local toolchain
        run: |
          rustup update
          rustup component add rustfmt
      - name: Check formatting
        run: cargo fmt -- --check

  clippy:
    runs-on: ubuntu-latest
    if: success() || failure()
    steps:
      - uses: actions/checkout@v3
      - name: Update local toolchain
        run: |
          rustup update
          rustup component add rustfmt
          rustup component add clippy
          rustup install nightly 
      - name: Check Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
  
  test:
    runs-on: ubuntu-latest
    if: success() || failure()
    steps:
      - uses: actions/checkout@v3
      - name: Update local toolchain
        run: |
          rustup update
          rustup install nightly 
      - name: Run tests
        run: cargo test --all-features